from rag_gt.validation.gt_quality import score_generated_pair


def test_flags_deictic_distribution_question():
    facts = [
        {
            "text": "One advantage of this distribution is that it is easily gener-",
            "supporting_spans": [
                {"doc_id": "doc", "chunk_id": "doc_c0010"},
            ],
        },
        {
            "text": "Intuitively it seems like a good choice, at least better than the uniform distribution.",
            "supporting_spans": [
                {"doc_id": "doc", "chunk_id": "doc_c0011"},
            ],
        },
    ]
    result = score_generated_pair(
        "Why is this distribution considered a better choice than the uniform distribution?",
        "It is preferable because it can be generated easily and seems better than a uniform distribution.",
        facts,
    )
    assert result["quality"] < 0.7
    assert result["flags"]["Q1_deictic_no_antecedent"]
    assert result["flags"]["Q4_generic_referent"]
    assert result["flags"]["Q7_bad_fact_fragment"]


def test_flags_generic_description_question():
    facts = [
        {
            "text": "Both compute the sets of present features corresponding to the current state and all possible actions.",
            "supporting_spans": [
                {"doc_id": "doc", "chunk_id": "doc_c0010"},
            ],
        },
        {
            "text": "state and action sets.",
            "supporting_spans": [
                {"doc_id": "doc", "chunk_id": "doc_c0011"},
            ],
        },
    ]
    result = score_generated_pair(
        "According to the description, which two kinds of sets are computed for the current state and for all possible actions?",
        "The method computes state sets and action sets.",
        facts,
    )
    assert result["quality"] < 0.7
    assert result["flags"]["Q4_generic_referent"]
    assert result["flags"]["Q7_bad_fact_fragment"]


def test_flags_given_statements_question():
    result = score_generated_pair(
        "Which two formal concepts are introduced for reinforcement learning in the given statements?",
        "The two concepts are vπ(s) and the Markov property.",
        [
            {
                "text": "The Markov property is formally defined for reinforcement learning.",
                "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}],
            }
        ],
    )

    assert result["quality"] < 0.7
    assert result["flags"]["Q4_generic_referent"]

    result = score_generated_pair(
        "According to the facts, why are sample backups useful?",
        "Sample backups can improve many state-action values quickly.",
        [
            {
                "text": "A few sample backups can improve many state-action values quickly.",
                "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}],
            }
        ],
    )

    assert result["quality"] < 0.7
    assert result["flags"]["Q4_generic_referent"]


def test_accepts_self_contained_question():
    facts = [
        {
            "text": "On-policy backup distribution is generated by interacting with the model while following the current policy.",
            "supporting_spans": [
                {"doc_id": "doc", "chunk_id": "doc_c0010"},
            ],
        },
        {
            "text": "The on-policy backup distribution is considered better than the uniform distribution.",
            "supporting_spans": [
                {"doc_id": "doc", "chunk_id": "doc_c0011"},
            ],
        },
    ]
    result = score_generated_pair(
        "Why is the on-policy backup distribution preferred over a uniform backup distribution?",
        "It is preferred because it can be generated by interacting with the model while following the current policy.",
        facts,
    )
    assert result["quality"] >= 0.7
    assert not any(result["flags"].values())


def test_flags_fact_without_chunk_id():
    result = score_generated_pair(
        "What does the backup update use to revise the state-value estimate?",
        "The backup uses possible successor states to revise the estimate.",
        [
            {
                "text": "Each backup updates the value of one state based on possible successor states.",
                "supporting_spans": [{"doc_id": "doc", "chunk_id": ""}],
            }
        ],
    )
    assert result["flags"]["Q7_bad_fact_fragment"]


def test_flags_answer_reasoning_leak():
    result = score_generated_pair(
        "Why do mobile telephone systems reuse channels?",
        "We need to answer the question. Wait the facts say channel reuse is possible.",
        [
            {
                "text": "A communication channel can be used simultaneously by many callers if they are spaced far enough apart.",
                "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}],
            }
        ],
    )
    assert result["quality"] < 0.7
    assert result["flags"]["Q8_answer_leaks_reasoning"]


def test_flags_weak_required_evidence():
    result = score_generated_pair(
        "How do the ideas and methods relate before the conclusion?",
        "The ideas and methods blend into each other and can be combined in many ways.",
        [
            {
                "text": "Before we are done, we will see that these ideas and methods blend into each other and can be combined in many ways.",
                "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}],
            }
        ],
    )
    assert result["flags"]["Q9_weak_required_evidence"]


def test_flags_bibliography_required_evidence():
    result = score_generated_pair(
        "What report number is listed for the Air Force Cambridge Research Laboratories entry?",
        "The entry lists Technical Report AFCRL-72-0164.",
        [
            {
                "text": "Technical Report AFCRL-72-0164, Air Force Cambridge Research Laboratories, Bedford, MA.",
                "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}],
            }
        ],
    )
    assert result["quality"] < 0.7
    assert result["flags"]["Q9_weak_required_evidence"]


def test_flags_fact_ending_mid_sentence():
    result = score_generated_pair(
        "What remains undetected during design?",
        "Missing requirements remain undetected during design.",
        [
            {
                "text": "Missing requirements often remain undetected during design and",
                "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}],
            }
        ],
    )

    assert result["quality"] < 0.7
    assert result["flags"]["Q7_bad_fact_fragment"]


def test_flags_fact_with_page_heading_prefix():
    result = score_generated_pair(
        "How many criteria are listed?",
        "Four criteria are listed.",
        [
            {
                "text": "94 7 Requirements Validation and Negotiation Requirements validation applies four criteria.",
                "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}],
            }
        ],
    )

    assert result["quality"] < 0.7
    assert result["flags"]["Q7_bad_fact_fragment"]


def test_flags_answer_is_question():
    result = score_generated_pair(
        "What does the control method estimate?",
        "What does the control method estimate?",
        [{"text": "The control method estimates action values.", "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}]}],
    )

    assert result["quality"] < 0.7
    assert result["flags"]["Q10_answer_is_question"]


def test_flags_answer_abstention_and_tautology():
    result = score_generated_pair(
        "Why is on-policy sampling useful?",
        "Insufficient information to answer.",
        [{"text": "On-policy sampling follows the current policy.", "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}]}],
    )
    assert result["flags"]["Q12_answer_abstains"]

    result = score_generated_pair(
        "Why is on-policy sampling useful?",
        "The facts explain why it can now be explained.",
        [{"text": "On-policy sampling follows the current policy.", "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}]}],
    )
    assert result["flags"]["Q13_answer_tautology"]


def test_flags_answer_heading_leak_and_short_fragment():
    result = score_generated_pair(
        "How does the algorithm update values?",
        "Chapter 4.3",
        [{"text": "The algorithm updates values using sampled returns.", "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}]}],
    )
    assert result["flags"]["Q11_answer_source_heading_leak"]
    assert result["flags"]["Q14_answer_fragment"]

    result = score_generated_pair(
        "Why are linear methods appealing?",
        "9.2 Gradient-descent methods are well known.",
        [{"text": "Linear methods are appealing theoretically.", "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}]}],
    )
    assert result["flags"]["Q11_answer_source_heading_leak"]

    result = score_generated_pair(
        "What should be initialized?",
        "ELIGIBILITY TRACES: Initialize Q(s, a).",
        [{"text": "Initialize Q(s, a).", "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}]}],
    )
    assert result["flags"]["Q11_answer_source_heading_leak"]


def test_short_entity_lookup_answer_is_allowed():
    result = score_generated_pair(
        "What value is used for epsilon?",
        "0.1",
        [{"text": "The epsilon value is 0.1.", "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}]}],
    )

    assert not result["flags"]["Q14_answer_fragment"]


def test_flags_source_artifact_questions_from_review_sample():
    fact = {
        "text": "Planning and Learning with Tabular Methods covers tabular planning.",
        "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}],
    }

    bad_questions = [
        "Which chapter is titled “Planning and Learning with Tabular Methods” and discusses covering the state space rather than focusing only where it is needed?",
        "What is the publishing house and city for the 2009 work authored by Koller and Friedman?",
        "What is the title of the review that discusses learning control systems and provides an outlook?",
        "What are the page ranges indicated for the two references titled Artificial Intelligence in the provided facts?",
        "What are the three page numbers on which the entries titled “Other Frontier Dimensions” appear?",
        "What are the two publications mentioned that address connectionist problem solving and learning?",
        "Which university's Department of Computer Science is located in Pittsburgh, Pennsylvania, United States?",
    ]

    for question in bad_questions:
        result = score_generated_pair(question, "A long enough grounded answer.", [fact])
        assert result["quality"] < 0.7
        assert result["flags"]["Q15_source_artifact_question"]


def test_flags_question_prompt_leak():
    result = score_generated_pair(
        "Check length: Count words: In which publication did the term reinforcement first appear? That's 12 words, meets min 12.",
        "The term appeared in Pavlov's monograph on conditioned reflexes.",
        [
            {
                "text": "The term reinforcement first appeared in this context in Pavlov's monograph on conditioned reflexes.",
                "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}],
            }
        ],
    )

    assert result["quality"] < 0.7
    assert result["flags"]["Q16_question_prompt_leak"]


def test_flags_question_prompt_leak_candidate_planning_text():
    result = score_generated_pair(
        'Maybe we can ask "How many hosts are identified by a network layer address?" Answer unknown.',
        "Hosts have network layer addresses.",
        [
            {
                "text": "Hosts have network layer addresses.",
                "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}],
            }
        ],
    )

    assert result["quality"] < 0.7
    assert result["flags"]["Q16_question_prompt_leak"]


def test_flags_question_prompt_leak_instruction_conflict_text():
    result = score_generated_pair(
        "We have a conflict: The user first gave a set of requirements for a single-fact question. What criterion applies?",
        "Requirements validation succeeds when no significant errors are found.",
        [
            {
                "text": "Requirements validation succeeds when no significant errors are found.",
                "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}],
            }
        ],
    )

    assert result["quality"] < 0.7
    assert result["flags"]["Q16_question_prompt_leak"]


def test_flags_two_item_question_with_one_item_answer():
    result = score_generated_pair(
        "What two primary functional requirements must a congestion control scheme satisfy?",
        "Congestion control must be fair.",
        [
            {
                "text": "The congestion control scheme must avoid congestion.",
                "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}],
            },
            {
                "text": "The congestion control scheme should be fair.",
                "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0011"}],
            },
        ],
    )

    assert result["quality"] < 0.7
    assert result["flags"]["Q17_cardinality_answer_mismatch"]


def test_flags_how_many_question_without_numeric_answer():
    result = score_generated_pair(
        "In a virtual-circuit network, how many network layer addresses are assigned to each host?",
        "Hosts in virtual circuit networks have network layer addresses.",
        [
            {
                "text": "Each host is identified by a network layer address.",
                "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}],
            }
        ],
    )

    assert result["quality"] < 0.7
    assert result["flags"]["Q18_numeric_answer_mismatch"]


def test_flags_unresolved_pdf_placeholders_in_facts_and_answer():
    result = score_generated_pair(
        "In which chapters are connections to psychology and neuroscience summarized?",
        "The connections are summarized in Chapters ?? and ??.",
        [
            {
                "text": "with connections to psychology and neuroscience summarized in Chapters ?? and ??.",
                "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}],
            }
        ],
    )

    assert result["quality"] < 0.7
    assert result["flags"]["Q19_unresolved_placeholder"]


def test_does_not_treat_normal_question_mark_as_placeholder():
    result = score_generated_pair(
        "Why is on-policy sampling useful?",
        "On-policy sampling is useful because it follows the current policy.",
        [
            {
                "text": "On-policy sampling follows the current policy.",
                "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}],
            }
        ],
    )

    assert not result["flags"]["Q19_unresolved_placeholder"]


def test_flags_phrase_lookup_question():
    result = score_generated_pair(
        "What capability is described by the phrase 'how appropriately it can generalize from past experience'?",
        "The phrase describes the ability to generalize from past experience.",
        [
            {
                "text": "A learning system can generalize appropriately from past experience.",
                "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}],
            }
        ],
    )

    assert result["quality"] == 0.0
    assert result["flags"]["Q20_phrase_lookup_question"]


def test_flags_that_situation_question():
    result = score_generated_pair(
        "What is the other action that is said to occur in that situation in the future?",
        "Future actions may differ in similar situations.",
        [
            {
                "text": "Future actions may differ in similar situations.",
                "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}],
            }
        ],
    )

    assert result["quality"] == 0.0
    assert result["flags"]["Q20_phrase_lookup_question"]


def test_q7_catches_truncated_verb_ending_fact():
    """Q7 via WEAK_FACT_END_RE catches facts ending with bare transitive verbs (truncated sentences)."""
    truncated_facts = [
        "Camerer (2003) discusses the reinforcement learning tradition in economics, and Nowé et al. (2012) provide",
        "These methods describe",
        "The algorithm can include",
        "Researchers subsequently demonstrate",
    ]
    for fact_text in truncated_facts:
        result = score_generated_pair(
            "What does this describe?",
            "It describes the method.",
            [{"text": fact_text, "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}]}],
        )
        assert result["flags"]["Q7_bad_fact_fragment"], (
            f"Expected Q7 to flag truncated fact: {fact_text!r}"
        )


def test_flags_planning_monologue_in_question():
    result = score_generated_pair(
        "We need a specific answer: maybe 'X'. Combine with second: Y. So question: What is the definition?",
        "The definition is X.",
        [{"text": "X is defined as Y.", "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}]}],
    )
    assert result["quality"] == 0.0
    assert result["flags"]["Q16_question_prompt_leak"]


def test_flags_in_the_statement_question():
    result = score_generated_pair(
        "Which technique is cited as an example in the statement?",
        "Dynamic programming is cited as an example.",
        [{"text": "of optimal control, such as dynamic programming,", "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}]}],
    )
    assert result["quality"] < 0.7
    assert result["flags"]["Q4_generic_referent"]


def test_flags_referred_to_in_the_phrase_question():
    result = score_generated_pair(
        "What is the name of the individual referred to in the phrase 'Whether he is aware of it or not, Phil'?",
        "The individual referred to is Phil.",
        [{"text": "Whether he is aware of it or not, Phil", "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}]}],
    )
    assert result["quality"] == 0.0
    assert result["flags"]["Q20_phrase_lookup_question"]


def test_flags_so_maybe_word_count_planning_leak():
    """Q16 catches 'so maybe:' and inline word-count deliberation leaking into question."""
    result = score_generated_pair(
        'But we need to name the concept: "natural language". So maybe: "What documentation approach is used?" Count: "What"(1)',
        "Natural language.",
        [{"text": "Requirements are documented in natural language.", "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c001"}]}],
    )
    assert result["quality"] == 0.0
    assert result["flags"]["Q16_question_prompt_leak"]


def test_q7_does_not_flag_complete_fact():
    """Q7 must not flag a complete, well-formed fact ending with a noun/adjective."""
    result = score_generated_pair(
        "What is a policy in reinforcement learning?",
        "A policy defines the agent's way of behaving at a given time.",
        [
            {
                "text": "A policy defines the learning agent's way of behaving at a given time.",
                "supporting_spans": [{"doc_id": "doc", "chunk_id": "doc_c0010"}],
            }
        ],
    )
    assert not result["flags"]["Q7_bad_fact_fragment"]
